# Generated by Django 2.2.4 on 2019-11-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptdata',
            name='realism',
            field=models.IntegerField(default=0, verbose_name='Валидность'),
        ),
    ]
