# Generated by Django 2.2.4 on 2019-09-19 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptdata',
            name='measurement_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Measure'),
        ),
    ]
