# Generated by Django 2.2.4 on 2019-11-21 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_acceptdata_realism'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptdata',
            name='realism',
            field=models.CharField(default='offline', max_length=10, verbose_name='Валидность'),
        ),
    ]
