# Generated by Django 2.2.4 on 2019-10-03 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191003_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreqRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_range', models.CharField(max_length=50, verbose_name='Входной диапазон')),
                ('output_range', models.CharField(max_length=50, verbose_name='Выходной диапазон')),
            ],
        ),
        migrations.AddField(
            model_name='ssi',
            name='freqrange',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.FreqRange', verbose_name='Частотный диапазон'),
            preserve_default=False,
        ),
    ]
