# Generated by Django 2.2.4 on 2019-08-29 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_measuretype'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasureResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('measurement_data', models.ManyToManyField(related_name='meas_result', to='app.MeasureType')),
                ('mesure_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.MeasureType')),
                ('ssi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.SSI')),
            ],
        ),
    ]
