# Generated by Django 2.2.4 on 2019-09-25 10:35

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190919_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measuretype',
            name='name',
            field=multiselectfield.db.fields.MultiSelectField(max_length=50, verbose_name='Тип измерения'),
        ),
    ]
