# Generated by Django 2.2.4 on 2019-10-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191003_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssi',
            name='input_frequency',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Входная частота'),
        ),
        migrations.AlterField(
            model_name='ssi',
            name='output_frequency',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Выходная частота'),
        ),
    ]
