# Generated by Django 2.2.4 on 2019-11-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191121_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptdata',
            name='realism',
            field=models.IntegerField(default=0, verbose_name='Реальность измерений:'),
        ),
    ]
