# Generated by Django 2.2.4 on 2019-08-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_measureresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasureData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='measureresult',
            name='measurement_data',
            field=models.ManyToManyField(related_name='meas_result', to='app.MeasureData'),
        ),
    ]
