# Generated by Django 2.2.4 on 2019-09-25 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190925_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measuretype',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Тип измерения'),
        ),
    ]
