# Generated by Django 2.2.4 on 2019-10-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191003_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssi',
            name='input_frequency',
            field=models.CharField(max_length=10, verbose_name='Входная частота'),
        ),
        migrations.AlterField(
            model_name='ssi',
            name='output_frequency',
            field=models.CharField(max_length=10, verbose_name='Выходная частота'),
        ),
    ]
