# Generated by Django 2.2.4 on 2019-11-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20191121_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptdata',
            name='realism',
            field=models.BooleanField(default=0, verbose_name='Реальность измерений:'),
        ),
    ]
