# Generated by Django 2.2.4 on 2019-10-04 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20191003_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssi',
            name='input_frequency',
            field=models.FloatField(verbose_name='Входная частота'),
        ),
        migrations.AlterField(
            model_name='ssi',
            name='output_frequency',
            field=models.FloatField(verbose_name='Выходная частота'),
        ),
    ]
