# Generated by Django 2.2.4 on 2019-08-30 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190829_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='ssi',
            name='name',
            field=models.CharField(default='1', max_length=50),
            preserve_default=False,
        ),
    ]
