# Generated by Django 2.2.4 on 2019-09-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190925_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measuretype',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Тип измерения'),
        ),
    ]
