# Generated by Django 2.2.4 on 2019-09-02 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_ssi_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ssi',
            name='measurement_type',
            field=models.ManyToManyField(related_name='meas_result', to='app.MeasureType'),
        ),
    ]
