# Generated by Django 2.2.4 on 2019-09-04 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_ssi_measurement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssi',
            name='measurement_type',
            field=models.ManyToManyField(to='app.MeasureType'),
        ),
    ]
