# Generated by Django 2.2.4 on 2019-10-04 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20191004_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ssi',
            name='freqrange',
        ),
        migrations.AddField(
            model_name='freqrange',
            name='ssi',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='freqrange', to='app.SSI'),
            preserve_default=False,
        ),
    ]
