# Generated by Django 2.2.4 on 2019-10-04 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20191004_1711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freqrange',
            old_name='ssi',
            new_name='ssi_element',
        ),
    ]
