# Generated by Django 2.2.4 on 2019-09-04 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190904_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ssi',
            name='measurement_type',
        ),
        migrations.AddField(
            model_name='ssi',
            name='meas_type',
            field=models.ManyToManyField(related_name='meas_type', to='app.MeasureType'),
        ),
    ]
