# Generated by Django 2.2.4 on 2019-09-27 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_operator'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Operator',
        ),
    ]
