# Generated by Django 2.2.4 on 2019-09-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20190904_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssi',
            name='meas_type',
            field=models.ManyToManyField(to='app.MeasureType'),
        ),
    ]
