# Generated by Django 2.2.4 on 2019-10-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20191004_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='freqrange',
            name='name',
            field=models.CharField(default=1, max_length=50, verbose_name='Имя диапазона'),
            preserve_default=False,
        ),
    ]
