# Generated by Django 2.2.4 on 2019-10-02 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_operator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measure',
            options={'permissions': (('make_measures', 'проводит измерения'),)},
        ),
    ]
