# Generated by Django 2.2.4 on 2019-09-04 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20190904_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssi',
            name='meas_type',
            field=models.ManyToManyField(related_name='SSis', to='app.MeasureType'),
        ),
    ]
