# Generated by Django 2.2.4 on 2019-10-10 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20191010_1126'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='freqrange',
            managers=[
            ],
        ),
    ]
