# Generated by Django 2.2.4 on 2019-09-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20190904_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='measuretype',
            name='friends',
            field=models.ManyToManyField(related_name='_measuretype_friends_+', to='app.MeasureType'),
        ),
    ]
