# Generated by Django 2.2.4 on 2019-10-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20191010_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssi',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Имя SSI'),
        ),
    ]
