# Generated by Django 2.2.4 on 2019-09-04 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_measuretype_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measuretype',
            name='friends',
        ),
    ]
