# Generated by Django 2.2.4 on 2019-09-10 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20190910_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measureresult',
            name='ssi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meas', to='app.SSI'),
        ),
        migrations.AlterField(
            model_name='ssi',
            name='meas_type',
            field=models.ManyToManyField(related_name='ssi', to='app.MeasureType'),
        ),
    ]
