# Generated by Django 2.2.4 on 2019-09-10 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20190910_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('meastype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measure', to='app.MeasureType')),
                ('measurement_data', models.ManyToManyField(related_name='meas_result', to='app.MeasureData')),
                ('ssi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meas', to='app.SSI')),
            ],
        ),
        migrations.DeleteModel(
            name='MeasureResult',
        ),
    ]
