# Generated by Django 2.2.4 on 2019-09-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20190910_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ssi', models.CharField(max_length=50)),
                ('input_freq', models.IntegerField()),
                ('output_freq', models.IntegerField()),
                ('data', models.FloatField()),
            ],
        ),
    ]
