# Generated by Django 2.2.4 on 2019-09-16 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_evidence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidence',
            name='input_freq',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='output_freq',
        ),
    ]
