# Generated by Django 2.2.4 on 2019-09-17 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20190916_2048'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MeasureData',
            new_name='AcceptData',
        ),
        migrations.RenameModel(
            old_name='Measure',
            new_name='Measure_common',
        ),
        migrations.DeleteModel(
            name='Evidence',
        ),
    ]
