# Generated by Django 2.2.4 on 2019-09-17 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20190917_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measure_que',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('meastype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measure', to='app.MeasureType')),
                ('ssi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meas', to='app.SSI')),
            ],
        ),
        migrations.DeleteModel(
            name='Measure_common',
        ),
    ]
