# Generated by Django 2.2.4 on 2019-09-17 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20190917_1808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ssi',
            old_name='available_meas',
            new_name='meas_type',
        ),
    ]
