# Generated by Django 2.2.4 on 2019-09-17 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20190917_1814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ssi',
            old_name='meas_type',
            new_name='available_meas',
        ),
    ]
